Repository hop-protocol/hop, pull requests merged in 2022-03, with the labels that each got.

#412 sdk: Set chainId for tx payload when sending
  packages/sdk/package.json
  packages/sdk/src/AMM.ts
  packages/sdk/src/Base.ts
  packages/sdk/src/HopBridge.ts
  packages/sdk/src/Token.ts
Labels: sdk, medium priority, ready for review

#411 UI: add sourceChain catch-all check to txConfirm hook
  packages/frontend/src/components/txConfirm/AddLiquidity.tsx
  packages/frontend/src/components/txConfirm/Approval.tsx
  packages/frontend/src/components/txConfirm/ConfirmConvert.tsx
  packages/frontend/src/components/txConfirm/ConfirmSend.tsx
  packages/frontend/src/components/txConfirm/ConfirmStake.tsx
  packages/frontend/src/components/txConfirm/RemoveLiquidity.tsx
  packages/frontend/src/components/txConfirm/UnwrapToken.tsx
  packages/frontend/src/components/txConfirm/WithdrawReview.tsx
  packages/frontend/src/components/txConfirm/WrapToken.tsx
  packages/frontend/src/components/txConfirm/useSendingTransaction.ts
  packages/frontend/src/hooks/useApprove.ts
  packages/frontend/src/pages/Withdraw/Withdraw.tsx
  packages/frontend/src/utils/constants.ts
  packages/frontend/src/utils/index.ts
Labels: ui

#408 UI: Add support for disabling network-specific txs
  packages/frontend/src/components/Link/Link.tsx
  packages/frontend/src/config/disabled.test.ts
  packages/frontend/src/config/disabled.ts
  packages/frontend/src/hooks/index.ts
  packages/frontend/src/hooks/useDisableTxs.ts
  packages/frontend/src/pages/Send/Send.tsx
  packages/frontend/src/utils/networks.test.ts
  packages/frontend/src/utils/networks.ts
  packages/sdk/yarn.lock
Labels: ui, maintenance

#420 UI: fix stats page
  packages/frontend/package.json
  packages/frontend/src/components/Table/Table.tsx
  packages/frontend/src/config/interfaces.ts
  packages/frontend/src/hooks/useGnosisSafeTransaction.ts
  packages/frontend/src/hooks/useSelectedNetwork.ts
  packages/frontend/src/models/Network.ts
  packages/frontend/src/pages/Stats/DebitWindowStats.tsx
  packages/frontend/src/pages/Stats/PendingAmountStats.tsx
  packages/frontend/src/pages/Stats/PoolStats.tsx
  packages/frontend/src/pages/Stats/StatsContext.tsx
  packages/frontend/yarn.lock
  packages/sdk/src/Base.ts
  packages/sdk/src/HopBridge.ts
  packages/sdk/src/config/metadata.ts
  packages/sdk/src/models/Chain.ts
Labels: bug, enhancement, ui, low priority
